version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.11.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: fredag13
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "key": "-----BEGIN CERTIFICATE-----\nMIIDBzCCAe+gAwIBAgIJRg6R17grT1FiMA0GCSqGSIb3DQEBCwUAMCExHzAdBgNV\nBAMTFnRlY2hyYWRhci5ldS5hdXRoMC5jb20wHhcNMjIwNzI5MTkyODM5WhcNMzYw\nNDA2MTkyODM5WjAhMR8wHQYDVQQDExZ0ZWNocmFkYXIuZXUuYXV0aDAuY29tMIIB\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyWf42AG6602quVGv1wqAtrND\n6emfLgseBL4/JunvMnU/ZrM18y/hWw/nIr7QTkGL+1kxZAsVExz1C9QknBvuc6+y\ntjkI+Rw2PegtDlXc3x1QD37BfHhJy0ieeLjf3KUGMPmMXezRDkKpyNRYK1w/Oq3U\nWz2tdDmtieGcBbBZljXHop5x+WUCJ/503JsQmKu+0udHKBT1J4Amf94xpibsjsY0\n8QN4qM8hZp5/ppS/8Y/OE7rlONOIpcezBVFjUQIyadd19CDyl/H8DcM/d3b1cihR\ny67XROSLsOtHDRchW2/f1N80qr5vuf4szC/0TRUSSBf6AAjS42k5YqvnqjrXTwID\nAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQdlyHZF2wOWetAtvvn\n0FaranW04DAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBABv2vsme\neWOIbPT0owmj0q1geArDN0f5+lclLoh1s6yaZeSlNYBrJfZVW+A5XtoyaHEcFRq3\nuPu1eDgY/6KPgAps73Qr9LklubQgc6SGDgoRueqY8u6ee8bGqBXT7eGZZGGzQrT2\n2YKa49+NqiBQtHDZgp8OWvN5Stivmb2Jl+Ity6fWSFF3nz1f6Gb1DOx7uDvhWuus\nqAZ7Rrtg+fc9tBpaBNJfjmpbNtUj7RNBMWuLHGnAHQ1y/0pfgCoRU0CzUqR7mOo8\nvL5QkF5fzJjI0ZC84LCNFKK0KiSD8hh5ed5pS5RI91Nni7kaKM2HEGFleBT1/Q8k\nXmt7gMlCNLxm+OU=\n-----END CERTIFICATE-----"}'
#      HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url": "https://techradar.auth0.com/.well-known/jwks.json","audience": "tech-radar"}'

      ## unauthorized role
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: unauthorized
volumes:
  db_data:

